services:
  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - "3005:3000"       # user truy cập http://domain.com:3001
    restart: always

  backend:
    build: ./back-end
    container_name: backend
    ports:
      - "3006:3000"   # user truy cập http://domain.com:3002
    restart: always


